if !has('nvim') | finish | endif

" Set syntax scheme to json and format it (by using python, make sure it is installed)
command Json set syntax=json | execute '%!python -m json.tool'


let g:gitgutter_map_keys = 0
"
let g:ctrlsf_auto_close = {
      \ "normal" : 0,
      \ "compact": 0
      \}
let g:ctrlsf_default_view_mode = 'compact'
let g:ctrlsf_backend = 'rg'

" Disable preview window (for e.g. :GFiles)
let g:fzf_preview_window = ''

let g:NERDCustomDelimiters = {
      \ 'javascript.tsx': { 'left': '//', 'leftAlt': '{/*', 'rightAlt': '*/}' },
      \ 'typescript.tsx': { 'left': '//', 'leftAlt': '{/*', 'rightAlt': '*/}' },
      \ 'svelte': { 'left': '<!--', 'right': '-->' },
      \ 'css': { 'left': '/*', 'right': '*/' }
      \ }

" NERDCommenter derives its delimiters from &filetype, so a markup buffer always
" comments as markup, even inside a <script> or <style> block. Swap the filetype
" for the duration of the call to get the embedded language's delimiters.
let s:embeddedTagFiletypes = { 'script': 'javascript', 'style': 'css' }
let s:markupFiletypes = ['html', 'svelte', 'vue']
let s:embeddedTagPattern = '<\/\?\%(' . join(keys(s:embeddedTagFiletypes), '\|') . '\)\>'

function! s:EmbeddedFiletype() abort
  for line in range(line('.') - 1, 1, -1)
    let tag = matchstr(getline(line), s:embeddedTagPattern)
    if tag ==# ''
      continue
    endif
    if tag =~# '^<\/'
      return ''
    endif
    return s:embeddedTagFiletypes[matchstr(tag, '\w\+')]
  endfor
  return ''
endfunction

function! NERDCommenter_before() abort
  if index(s:markupFiletypes, &filetype) < 0 || exists('b:nerd_outer_filetype')
    return
  endif
  let embedded_filetype = s:EmbeddedFiletype()
  if embedded_filetype ==# ''
    return
  endif
  let b:nerd_outer_filetype = &filetype
  noautocmd execute 'setlocal filetype=' . embedded_filetype
endfunction

function! NERDCommenter_after() abort
  if !exists('b:nerd_outer_filetype')
    return
  endif
  noautocmd execute 'setlocal filetype=' . b:nerd_outer_filetype
  unlet b:nerd_outer_filetype
endfunction

let g:vim_ai_chat = {
\  "options": {
\    "model": "gpt-4",
\  },
\}

let g:context_filetype_blacklist = ["NvimTree", "buffernavigator"]
let g:context_highlight_tag = '<hide>'
let g:context_add_mappings = 0
let g:context_enabled = 0

let g:mergetool_layout = 'b,mr'

" Disable this fix dince it has to side effects: It cancels commands and when
" opening a pane bc there is not yet one open, it does not run a proper zsh
" but a basic sh
" Actual fix: See https://github.com/preservim/vimux/issues/230
" to avoid the error message "E605: Exception not caught: Tmux command failed with message:not in a mode^@" when the target pane is scrolled
"let g:VimuxResetSequence = "C-c"

" =============================================================
" Coc Settings
" =============================================================

" if hidden is not set, TextEdit might fail.
set hidden

" Some servers have issues with backup files, see #649
" UPDATE: Re-enable backup for avoiding data-loss reasons, let's see whether coc can
" handle it...
"set nobackup
"set nowritebackup

" Better display for messages
set cmdheight=1

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json,svelte setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end


" Use `:Format` to format current buffer
command! -nargs=0 Format :call CocAction('format')

" Use `:Fold` to fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" use `:OR` for organize import of current buffer
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

let g:coc_snippet_next = '<tab>'

" coc needs Node >= 24.4 (vm moduleRequests); use the newest installed asdf node
" instead of inheriting the project's pin (asdf list sorts lexically, hence sort -V)
let s:newestNodeVersion = get(systemlist('ls ~/.asdf/installs/nodejs 2>/dev/null | sort -V | tail -1'), 0, '')
let s:cocNode = expand('~/.asdf/installs/nodejs/' . s:newestNodeVersion . '/bin/node')
if !empty(s:newestNodeVersion) && executable(s:cocNode)
  let g:coc_node_path = s:cocNode
else
  echohl WarningMsg
  echomsg 'coc: no node install under ~/.asdf/installs/nodejs, using $PATH node (coc-prettier needs >= 24.4)'
  echohl None
endif

"coc-emoji is triggered when typing ':'
let g:coc_global_extensions = [
      \'coc-snippets',
      \'coc-json',
      \'coc-tsserver',
      \'coc-prettier',
      \'coc-eslint',
      \'coc-css',
      \'coc-styled-components',
      \'https://github.com/andys8/vscode-jest-snippets',
      \'https://github.com/akamud/vscode-javascript-snippet-pack',
      \'@yaegassy/coc-tailwindcss3',
      \'coc-emmet',
      \'coc-pyright',
      \'coc-emoji',
      \'coc-dictionary',
      \'coc-word',
      \'coc-vimlsp',
      \'coc-sumneko-lua',
      \'coc-solargraph',
      \'coc-db',
      \]

" =============================================================
" End Coc Settings
" =============================================================

function! OpenRangerForCurrentFile()
  let bufferFilePath = expand('%') 
  VimuxRunCommand "ranger --selectfile='" . bufferFilePath . "'"
  VimuxZoomRunner
endfunction

function! JumpToSameIndent(direction, inVisualMode)
  let line = line('.')

  let currentLine = line
  let matchIndent = 0
  while !matchIndent && currentLine != line('$') + 1 && currentLine != -1
    let currentLine += a:direction == 'down' ? 1 : -1
    let lineText = getline(currentLine)
    let matchIndent = lineText !~ '^\s*$' && trim(lineText) !~ '^[\]\)\}]$' && indent(currentLine) == indent('.')
  endwhile

  if (matchIndent)
    if (a:inVisualMode)
      norm! gv
    endif

    execute 'norm! ' . currentLine . 'G'
  endif
endfunction

source $HOME/.dotfiles/vim/neovim/outline.vim
source $HOME/.dotfiles/vim/neovim/statusline.vim
source $HOME/.dotfiles/vim/neovim/present.vim
source $HOME/.dotfiles/vim/neovim/mappings.vim

let g:BufferNavigatorMapKeys = 0

" match buffer navigator colors with current theme
execute 'autocmd FileType buffernavigator highlight BufferNavigatorModifiedFile ctermfg=' . accentText . ' ctermbg=NONE' 
execute 'autocmd FileType buffernavigator highlight BufferNavigatorFile ctermfg=' . secondaryText . ' ctermbg=NONE' 

if dotfilesTheme =~ '-light$'
  autocmd FileType buffernavigator highlight BufferNavigatorDir ctermfg=0 ctermbg=NONE 
endif


" For whatever reason, vim started to set the filetype for *.html files to sh
augroup fixHtmlFiletype
  au!
  autocmd BufNewFile,BufRead *.html  set ft=html
augroup END

augroup filetype_gitcommit
    autocmd!
    autocmd FileType gitcommit iab <buffer> <expr> wip "wip [skip ci]"
augroup END

" rhysd/conflict-marker.vim
let g:conflict_marker_highlight_group = ''


let g:vim_svelte_plugin_use_typescript = 1

" Colour compound attributes (data-*, aria-*, class:*) as a whole. `data`,
" `prompt` and `class` are htmlArg keywords, and a keyword always wins over a
" match at the same start column — so `data-my-tooltip-prompt` renders in three
" colours and `class:active` in two. Matching from the separator dodges the
" keyword. An after/syntax file cannot do this: lazy.nvim drops ~/.vim/after
" from the runtimepath.
augroup compoundHtmlAttrs
  autocmd!
  autocmd Syntax html,svelte
        \ syn match htmlArg "\%([0-9A-Za-z]\)\@<=\%([-:][-.:0-9_A-Za-z]\+\)\+"
        \ contained containedin=htmlTag
augroup END

let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.tsx,*.jsx,*.svelte'
let test#strategy = "vimux"
let g:test#echo_command = 0

autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx

" Enable TOC window auto-fit
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_folding_disabled = 1


let g:vimtex_syntax_conceal_disable = 1

set dictionary+=/usr/share/dict/words

function! s:SpellCheck(bang, lang = "en")
  let prefix = ""
  if a:bang
    let prefix = "no" 
  endif
  execute "setlocal " . prefix . "spell spelllang=" . a:lang
endfunction

command! -nargs=? -bang SpellCheck :call <SID>SpellCheck(<bang>0, <f-args>)

function! s:ToggleWrite(bang, width)
  if a:bang
    Goyo! | Limelight!
    set nowrap nolinebreak
    colorscheme codedark
    hi Normal ctermbg=NONE
    hi EndOfBuffer ctermbg=NONE
    hi LineNr ctermbg=NONE
    hi SignColumn ctermbg=NONE
    nunmap <silent> <buffer> j
    nunmap <silent> <buffer> k
  else
    set wrap linebreak
    colorscheme seoul256
    execute "Goyo " . a:width . " | Limelight"
    nnoremap <silent> <buffer> j gj
    nnoremap <silent> <buffer> k gk
  endif
endfunction

command! -nargs=* -bang Write :call <SID>ToggleWrite(<bang>0, <q-args>)


let g:statuslineMode = "default"

" TODO :so can handle visual selection by itself, writing to tmp file necessary??
" TODO Add possibility for running vim9 scripts (:vim9 so)
function! SourceSelection() range
  let tmpFile = tempname()
  call writefile(getline(a:firstline, a:lastline), l:tmpFile)
  execute "source " . l:tmpFile
  call delete(l:tmpFile)
endfunction
command! -range SourceSelection let b:winview = winsaveview() | <line1>,<line2>call SourceSelection() | call winrestview(b:winview) | unlet b:winview

command! Themis :VimuxRunCommand expand("$HOME") . "/.vim/vim-plug/vim-themis/bin/themis " . expand("%")

function! ToggleStatusline()
  if g:statuslineMode == "default"
    let g:statuslineMode = "syntax"
    let &statusline = ' %{synIDattr(synID(line("."),col("."),1),"name")} - %{synIDattr(synIDtrans(synID(line("."),col("."),1)),"name")} '
  else
    let g:statuslineMode = "default"
    set statusline=%!StatusLine()
  endif 
endfunction


function! s:AlternateSafe()
  try
    A
  catch /^Vim\%((\a\+)\)\=:E345:/
    let path = matchstr(v:exception, '.*"\zs.*\ze".*')
    execute 'e ' . path
  endtry
endfunction

command! AlternateSafe :call <SID>AlternateSafe()

let g:projectionist_heuristics = { ".git/":
      \ { "lib/web/*_controller.rb": { "alternate": [ "spec/web/{}_request_spec.rb", 
      \                                               "spec/web/{}_get_request_spec.rb", 
      \                                               "spec/web/{}_post_request_spec.rb", 
      \                                               "spec/web/{}_patch_request_spec.rb", 
      \                                               "spec/web/{}_delete_request_spec.rb"] }, 
      \   "spec/web/*_get_request_spec.rb": { "alternate": "lib/web/{}_controller.rb" },
      \   "spec/web/*_post_request_spec.rb": { "alternate": "lib/web/{}_controller.rb" },
      \   "spec/web/*_patch_request_spec.rb": { "alternate": "lib/web/{}_controller.rb" },
      \   "spec/web/*_delete_request_spec.rb": { "alternate": "lib/web/{}_controller.rb" },
      \   "spec/web/*_request_spec.rb": { "alternate": "lib/web/{}_controller.rb" }}
      \ }

augroup filetype_ruby
    autocmd!
    let rubySynGroups = ["rubyString", "rubyComment"]
    autocmd FileType ruby iab <buffer> <expr> de ExcludeSynGroupAbbr("de", "do<cr>end<esc>O", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> it ExcludeSynGroupAbbr("it", "it 'does' do<cr>end<esc>O", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> ctx ExcludeSynGroupAbbr("ctx", "context 'with sth' do<cr>end<esc>O", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> def ExcludeSynGroupAbbr("def", "def<cr>end<esc>kA", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> class ExcludeSynGroupAbbr("class", "class<cr>end<esc>kA", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> if ExcludeSynGroupAbbr("if", "if<cr>end<esc>kA", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> pry ExcludeSynGroupAbbr("pry", "require 'pry'; binding.pry", rubySynGroups)
    autocmd FileType ruby iab <buffer> <expr> irb ExcludeSynGroupAbbr("irb", "binding.irb", rubySynGroups)

augroup END

augroup skeletons_ruby
  autocmd BufNewFile,BufReadPost *_spec\.rb if getline(1,'$') == [''] | 0r $HOME/.dotfiles/vim/neovim/skeletons/spec.rb | endif
  autocmd BufNewFile,BufReadPost *.rb if getline(1,'$') == [''] | 0r $HOME/.dotfiles/vim/neovim/skeletons/ruby.rb | endif
augroup END

let g:BufferNavigatorWidth = 50
let g:BufferNavigatorHighlightRules = [
      \["rubySpecDir", "dir", "spec", "NONE", "106", "NONE", "green"],
      \["rubySpecFile", "file", ".*_spec\.rb", "NONE", "154", "NONE", "green"],
      \]


let g:copilot_settings = #{selectedCompletionModel: 'gpt-4o-copilot'}
let g:copilot_filetypes = {
      \ 'gitcommit': v:true,
      \ }

