let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.tsx, *.jsx'
let test#strategy = "vimux"
let g:test#echo_command = 0

autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx

let g:coc_global_extensions = g:coc_global_extensions + [
      \'coc-json',
      \'coc-tsserver',
      \'coc-prettier',
      \'coc-eslint',
      \'coc-css',
      \'coc-styled-components',
      \'https://github.com/andys8/vscode-jest-snippets',
      \'https://github.com/akamud/vscode-javascript-snippet-pack',
      \'@yaegassy/coc-tailwindcss3',
      \'coc-emmet',
      \]

source $HOME/.dotfiles/vim/web/mappings.vim
