let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.tsx, *.jsx'
let test#strategy = "vimux"

autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx

source $HOME/.dotfiles/vim/web/coc.vim
source $HOME/.dotfiles/vim/web/mappings.vim
