#!/usr/bin/env zsh

{
    read -r state
    read -r value
} <<< "$(source $HOME/.dotfiles/tmux/battery.linux.zsh)"

if [[ -z $value ]]
then
    echo "No battery"
    exit
fi

if [[ "$state" = "charging" ]]
then
    echo "<span color='#22be5e'>$value%</span>"
elif [[ $value -lt 16 ]]
then
    if [[ "$(($(date '+%s') % 2))" = "1" ]]
    then
        echo "<span background='#b92500' color='white' weight='bold'> $value% </span>"
    else
        echo "<span weight='bold'> $value% </span>"
    fi
elif [[ $value -lt 31 ]]
then
    echo "<span color='#f8e90d' weight='bold'>$value%</span>"
else
    echo "$value%"
fi



