#!/usr/bin/env sh

# free + 0: Make sure free is treated as a number
df -hl / | tail -1 | awk '
/\/.*/ {
	free=$4
  gsub(/G$/, "", free)

  print free " GB"
  print free " GB"

	if ((free + 0) < 10) {
		print "#f8e90d"
	}
}
'
