#!/usr/bin/env zsh

if [[ $1 = "up" ]]
then
    amixer -q -D pulse sset Master 5%+
elif [[ $1 = "down" ]]
then
    amixer -q -D pulse sset Master 5%-
elif [[ $1 = "toggle-mute" ]]
then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
elif [[ $1 = "toggle-mic-mute" ]]
then
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
fi

pkill -SIGRTMIN+10 i3blocks

{
    read -r value
    read -r mute
} <<< "$(source $HOME/.dotfiles/i3/get-volume)"


icon_high="audio-volume-high-symbolic"
icon_low="audio-volume-low-symbolic"
icon_muted="audio-volume-muted-symbolic"

if [[ $mute = "yes" ]]
then
    dunstify "Mute" -u low -i $icon_muted -h string:x-dunst-stack-tag:tkdf-volume-set -h int:value:$value
elif [[ $value -lt 50 ]]
then
    dunstify "Volume" -u low -i $icon_low -h string:x-dunst-stack-tag:tkdf-volume-set -h int:value:$value
else
    dunstify "Volume" -u low -i $icon_high -h string:x-dunst-stack-tag:tkdf-volume-set -h int:value:$value
fi


# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
