#!/usr/bin/env zsh

volume_high="\uf028"
volume_low="\uf027"
volume_off="\uf026"
volume_muted="\uf6a9"

{
    read -r value
    read -r mute
} <<< "$(source $HOME/.dotfiles/i3/get-volume)"

if [ "$mute" = "yes" ]
then
  echo "$volume_muted"
elif [[ $value -eq 0 ]]
then
  echo "$volume_off $value%"
elif [[ $value -lt 50 ]]
then
  echo "$volume_low $value%"
else
  echo "$volume_high $value%"
fi

