function! s:ToggleWrite(bang)
  if a:bang
    Goyo! | Limelight!
    set nowrap nolinebreak
    colorscheme codedark
  else
    set wrap linebreak
    colorscheme seoul256
    Goyo | Limelight
  endif
endfunction

command! -bang Write :call <SID>ToggleWrite(<bang>0)
