let g:coc_global_extensions = g:coc_global_extensions + ['coc-vimlsp']

" TODO :so can handle visual selection by itself, writing to tmp file necessary??
" TODO Add possibility for running vim9 scripts (:vim9 so)
function! SourceSelection() range
  let tmpFile = tempname()
  call writefile(getline(a:firstline, a:lastline), l:tmpFile)
  execute "source " . l:tmpFile
  call delete(l:tmpFile)
endfunction
command! -range SourceSelection let b:winview = winsaveview() | <line1>,<line2>call SourceSelection() | call winrestview(b:winview) | unlet b:winview

command! Themis :VimuxRunCommand expand("$HOME") . "/.vim/vim-plug/vim-themis/bin/themis " . expand("%")

source $HOME/.dotfiles/vim/viml/mappings.vim
