# See delta.dark.conf for the quoting caveat.
[delta]
    light = true
    minus-style = "syntax #ffd7d5"
    minus-emph-style = "syntax #ffaba8"
    plus-style = "syntax #d7f8dd"
    plus-emph-style = "syntax #9fe8b0"
    minus-empty-line-marker-style = "normal #ffd7d5"
    plus-empty-line-marker-style = "normal #d7f8dd"
    line-numbers-minus-style = "bold #cf222e"
    line-numbers-plus-style = "bold #1a7f37"
    line-numbers-zero-style = "#6e7781"
