#!/usr/bin/env ruby
# frozen_string_literal: true

require 'io/console'
require 'English'
require 'json'

module OS
  def self.mac?
    (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def self.linux?
    (/linux/ =~ RUBY_PLATFORM) != nil
  end
end

primary_text = ENV['primaryText'].sub(/colour/, '')
secondary_text = ENV['secondaryText'].sub(/colour/, '')
secondary_bg = ENV['secondaryBg']
secondary_fg = ENV['secondaryFg']
cache_time = 60

output = `gh api -i --cache #{cache_time}s notifications`
exit 1 unless $CHILD_STATUS.success?

# rate_limit_remaining = output.lines.find { |line| line.start_with?('X-Ratelimit-Remaining:') }.split(':').last.strip.to_i
# pp rate_limit_remaining

# Export in some way to use that for the next run as cache_time
# poll_interval = output.lines.find { |line| line.start_with?('X-Poll-Interval:') }.split(':').last.strip.to_i

json = output.split("\r\n").last
notifications = JSON.parse(json)

mentions = notifications.select { |item| item['reason'] == 'mention' }.length
prs = notifications.select { |item| item['subject']['type'] == 'PullRequest' }.length

if ARGV[0] == 'tile'
  puts "#[fg=#{secondary_fg},bg=#{secondary_bg}] #{prs.zero? ? '-' : prs}/#{mentions.zero? ? '-' : mentions} #[default] "
  exit 0
end

# TODO: Close only on 'q' and allow navigation with j/k and opening the links
grouped_by_repo = notifications.group_by { |item| item['repository']['full_name'] }
grouped_by_repo.sort.each do |repo, items|
  puts "\e[38;5;#{primary_text}m#{repo}\e[0m"
  items.each do |item|
    puts " - [#{item['subject']['type']}, #{item['reason']}] \e[38;5;#{secondary_text}m#{item['subject']['title']}\e[0m"
  end
end

input = $stdin.getch
if input == 'o'
  cmd = OS.linux? ? 'xdg-open' : 'open'
  `#{cmd} https://github.com/notifications`
end
