#!/usr/bin/env zsh

dotfilesRepo=${DOTFILES_REPO:-"tklepzig/dotfiles"}
dotfilesBranch=${DOTFILES_BRANCH:-"master"}

alias mkcd='function __mkcd() { mkdir "$1"; cd "$1"; unset -f __mkcd; }; __mkcd'

if isOS darwin
then
    alias ls='ls -FG'
else
    alias ls='ls -F --color=auto'
fi

alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -Ahl'

if isProgramInstalled eza
then
    alias ls='eza'
    alias la='eza -a'
    alias ll='eza -l'
    alias lla='eza -la'
fi

alias rmr='rm -rf'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias t='tmux new-session -n ""'
alias ta='tmux a'

alias dotfiles-update='/usr/bin/env ruby -e "$(curl -Ls https://raw.githubusercontent.com/$dotfilesRepo/$dotfilesBranch/setup.rb)"'
alias dfu='dotfiles-update'

alias notify="$dotfilesDir/notify.rb"
alias battery-monitor="$dotfilesDir/battery-monitor.rb"
if isOS linux
then
    alias n='nautilus .'
fi

if isOS darwin
then
    alias o='open .'
fi

alias git='LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 git'
alias g='git'
gcln() { source $HOME/.dotfiles/toolbox/scripts/git-clone-cd $1 }

alias ghs='gh status'
alias s='# stacked'
alias c='clear'
alias d='docker'
alias dc='docker compose'
alias dcu='docker compose up -d'
alias dcup='docker compose up --pull always -d'
alias dcd='docker compose down --remove-orphans'
alias dcdv='docker compose down --remove-orphans --volumes'
alias dce='docker compose exec'
alias dcl='docker compose logs -f'
alias dp='docker system prune -f && docker rmi -f $(docker images -q)'
alias ccp='xclip -selection clipboard'

if [ -n "$DOTFILES_NVIM" ]
then
    alias vim='nvim'
else
    alias vim='vim'
fi

alias v='vim'
alias vs='vim -S'

# Open all files of current branch
alias vbf="f() { vim \$(g bf \$1) }; f"

# Open all files which are currently changed or created (git diff)
alias vdf="f(){ git a; files=\$(git ds --name-only); git r; vim \$(echo \"\$files\"); unset -f f }; f"

# Open all files of a specific commit $1
alias vcf="f(){ vim \$(git show --pretty='format:' --name-only \"\$1\"); unset -f f }; f"

# Skip configuration and start vim without any config
alias vclean='vim -u /dev/null'

# With `. ranger` (or `source ranger`) the last visited directory will be used for the shell when exiting ranger
# If you want to go back where you left off, just enter `cd -`
# See also https://unix.stackexchange.com/a/570812 and https://github.com/ranger/ranger/blob/master/ranger.py
alias r='. ranger'

alias q='exit'
alias cf="cd \$(find * -type d | fzf)"
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ly="lynx -cfg $dotfilesDir/lynx.cfg"
alias ni='npm install'
alias nid='npm install -D'
alias nu='npm uninstall'
alias nr='npm run'
alias nrt='npm run test 2>&1 | grep ●'
alias niwt="f(){ npm i \$1 && npm i -D @types/\$1; unset -f f }; f"
alias nmc="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +"

alias pni='pnpm install'
alias pnid='pnpm install -D'
alias pnu='pnpm uninstall'
alias pnr='pnpm run'

alias b="bundle"
alias ba="bundle add"
alias bo="bundle open"
alias be="bundle exec"
alias ber="bundle exec rake"
alias berdb="bundle exec rake db:create db:migrate"
alias beru="ENV=test bundle exec rake unit"
alias beri="ENV=test bundle exec rake integration"
alias berui="ENV=test bundle exec rake unit integration"

alias ai="asdf install"

alias gpc="gpg --full-gen-key"
alias gpl="gpg --list-keys --with-subkey-fingerprints --keyid-format=short"
alias gpls="gpg --list-secret-keys --with-subkey-fingerprints --keyid-format=short"
gpe() {
    gpg --armor --export $1 > $1.pub
    gpg --armor --export-secret-keys $1 > $1.key
    gpg --output $1.rev --gen-revoke $1
}

if isProgramInstalled pacman
then
    alias pm='sudo pacman'
fi

# Passing aliases when using sudo
alias sudo='sudo '

# TODO
# add auto-increment number as prefix to every file (remove -n to apply changes)
#rename -n 's/(.+)/our $i; sprintf("%02d-$1", 1+$i++)/e' *

# Delete recursively all node_modules folders
#find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
