#!/usr/bin/env zsh

key_tuples=$(gpg --list-secret-keys --with-colons | awk -F: '
$1 == "sec" { expiration = $7 }
$1 == "uid" { print $10";"expiration }')

while IFS=$';' read -r uid expiration; do
  # Skip empty expiration dates
  if [[ -z $expiration ]]; then
    continue
  fi

  diff=$((expiration - $(date +%s)))
  if (( diff < 0 )); then
    echo "$uid expired $(( -diff / 86400 )) days ago"
  elif (( diff < 2592000 )); then
    echo "$uid expires in $(( diff / 86400 )) days"
  fi
done <<< "$key_tuples"

