#!/usr/bin/env ruby
# frozen_string_literal: true

DF_PATH = "#{ENV['HOME']}/.dotfiles".freeze
DF_LOCAL_PATH = "#{ENV['HOME']}/.dotfiles-local".freeze

def mac?
  (/darwin/ =~ RUBY_PLATFORM) != nil
end

def program_installed?(program)
  system("command -v #{program} > /dev/null 2>&1")
end

player = mac? ? 'afplay -v 0.2' : 'aplay'
exit(false) unless program_installed? player.split(/\s/).first

sound_path = "#{DF_LOCAL_PATH}/sounds/battery-alert.wav"
exit(false) unless File.exist? sound_path

loop do
  state, value = `#{DF_PATH}/tmux/battery.#{mac? ? 'osx' : 'linux'}.zsh`.split("\n")

  if state != 'charging' && value.to_i < 16
    `#{player} #{sound_path} > /dev/null 2>&1`
    sleep 2
    next
  end

  sleep 20
end
