#!/usr/bin/env zsh

git clone --no-checkout $1
cd "$(basename $1 .git)"
git config filter.encrypt.required true
git config filter.encrypt.clean "$HOME/.dotfiles/toolbox/misc/gpg-git-filter/clean $2"
git config filter.encrypt.smudge "$HOME/.dotfiles/toolbox/misc/gpg-git-filter/smudge $2"
git checkout
