#!/usr/bin/env ruby
# frozen_string_literal: true

require('securerandom')

length = (ARGV[0] || 16).to_i
chars = [*'A'..'Z', *'a'..'z', *'0'..'9', *'!'..'/', *':'..'@', '{', '}', '~']
puts SecureRandom.alphanumeric length, chars:
