#!/usr/bin/env zsh

defaultBranch=$(git rev-parse --verify --quiet refs/heads/master > /dev/null && echo master || echo main)
currentBranch=$(git rev-parse --abbrev-ref HEAD)

git rebase -i --autostash $(git log ${1:-$defaultBranch}..${2:-$currentBranch}  --oneline --pretty=format:'%h' | tail -1)^
