#!/usr/bin/env zsh

defaultBranch=$([ -f "$(git rev-parse --show-toplevel)/.git/refs/heads/master" ] && echo master || echo main)
currentBranch=$(git symbolic-ref HEAD)

git fetch
if [ "$1" = "--all" ]
then
    for branch in $(git for-each-ref --format='%(refname)' refs/heads/); do
        if [ $currentBranch != $branch ]
        then
            git fetch origin +$branch:$branch
        fi
    done
elif [ $currentBranch != refs/heads/$defaultBranch ]
then
    git fetch origin +$defaultBranch:$defaultBranch
fi

git fetch origin $currentBranch
git merge --ff-only
