#!/usr/bin/env zsh
isOS()
{
    shopt -s nocasematch
    if [[ "$OSTYPE" == *"$1"* ]]
    then
        return 0;
    fi

    return 1;
}
defaultBranch=$(git rev-parse --verify --quiet refs/heads/master > /dev/null && echo master || echo main)
currentBranch=$(git rev-parse --abbrev-ref HEAD)
cmd=$(isOS linux && echo "xdg-open" || echo "open")
remote=$(git remote get-url origin)
# for https
# TODO
#repoName=$(basename -s .git $remote)
#repoAndOrgName=${dirname -s .git $(git remote get-url origin))
# for ssh
orgAndRepo=${remote##*:}
orgAndRepo=${orgAndRepo/.git/$nop}

$cmd https://github.com/$orgAndRepo/compare/${1:-$defaultBranch}..${2:-$currentBranch}
