#!/usr/bin/env ruby
# frozen_string_literal: true

DF_LOCAL_PATH = "#{ENV['HOME']}/.dotfiles-local".freeze

def mac?
  (/darwin/ =~ RUBY_PLATFORM) != nil
end

def program_installed?(program)
  system("command -v #{program} > /dev/null 2>&1")
end

player = mac? ? 'afplay -v 0.2' : 'aplay'
exit(false) unless program_installed? player.split(/\s/).first

sound_path = "#{DF_LOCAL_PATH}/sounds/notify.wav"
exit(false) unless File.exist? sound_path

`#{player} #{sound_path} > /dev/null 2>&1`
