#!/usr/bin/env ruby
# frozen_string_literal: true

require "#{ENV['dotfiles_path']}/setup"

player = if OS.mac?
           'afplay -v 0.2'
         else
           'aplay'
         end
exit(false) unless program_installed? player.split(/\s/).first

sound_path = "#{DF_LOCAL_PATH}/sounds/notify.wav"
exit(false) unless File.exist? sound_path

`#{player} #{sound_path} > /dev/null 2>&1`
