#!/usr/bin/env zsh

#TODO: add option to specify start number
#TODO: add option to switch between dry-run and actual rename
start=1
ext="${1:-mp3}"

for file in *.$ext; do
  new=$(printf "%02d-$file" "$start") #02 pad to length of 2
  echo "Renaming $file to $new"
  #mv -i -- "$file" "$new"
  let start=start+1
done
