#!/usr/bin/env zsh

theme=$1
if [ -z $theme ]
then
  theme="${DOTFILES_THEME:-lcars}"
fi

cat $HOME/.dotfiles/themes/colours.$theme.zsh > $HOME/.dotfiles/colours.zsh


kitty_theme="dark"
if [[ "$theme" =~ "light" ]]
then
  kitty_theme="light"
fi
cat $HOME/.dotfiles/themes/kitty.$kitty_theme.conf > $HOME/.dotfiles/kitty/kitty.theme.conf

rm -f $HOME/.dotfiles/colours.vim
while read -r line
do
  [[ -z $line ]] && continue
  [[ $line =~ ^#.* ]] && continue
  echo "let $line" >> $HOME/.dotfiles/colours.vim
done <$HOME/.dotfiles/colours.zsh

# Reload tmux config if in tmux
if [ -n "$TMUX" ] && [ -f $HOME/.tmux.conf ]
then
  tmux source-file $HOME/.tmux.conf
fi

# Reload kitty config by sending SIGUSR1 to kitty process
pkill -USR1 kitty

# Update chosen theme in .zshrc
sed "/DOTFILES_THEME/d" $HOME/.zshrc > $HOME/.zshrc.tmp && mv $HOME/.zshrc.tmp $HOME/.zshrc
echo "export DOTFILES_THEME='$theme'" >> $HOME/.zshrc;
