#!/usr/bin/env zsh

if [ -d "$HOME/.asdf" ]
then
  echo "Warning: asdf already set up, exiting."
  exit 1
fi

git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
cd $HOME/.asdf
git checkout "$(git describe --abbrev=0 --tags)"
make
if ! grep -q 'export PATH="$HOME/.asdf:$PATH"' $HOME/.zshrc
then
  echo 'export PATH="$HOME/.asdf:$PATH"' >> $HOME/.zshrc;
  echo 'export PATH="$HOME/.asdf/shims:$PATH"' >> $HOME/.zshrc;
  mkdir -p "$HOME/.asdf/completions"
  source $HOME/.zshrc
  asdf completion zsh > "$HOME/.asdf/completions/_asdf"
  echo 'fpath=($HOME/.asdf/completions $fpath)' >> $HOME/.zshrc;
fi
cd -

source $HOME/.zshrc

for plugin in nodejs python ruby vim ctop neovim wrk github-cli gitui
do
  asdf plugin add $plugin
  asdf install $plugin latest
  asdf set -u $plugin latest
done



