#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'
require 'English'
require 'yaml'

class String
  def accent
    "\e[0;94m#{self}\e[0;34m"
  end

  def integer?
    to_i.to_s == self
  end
end

module Logger
  @level = 0

  def self.log(message)
    text_color = (ENV['primaryText'] || '4').sub(/colour/, '')

    prefix = @level.zero? ? "\e[1;38;5;#{text_color}m\u276f " : ''
    message = message.rjust(message.length + 2 * @level)
    puts "#{prefix}\e[0;38;5;#{text_color}m#{message}\e[0m"

    write_log_file(message)

    return unless block_given?

    @level += 1
    yield
    @level -= 1
    @level = 0 if @level.negative?
  end

  def self.success(message)
    text_color = (ENV['accentText'] || '6').sub(/colour/, '')

    prefix = @level.zero? ? "\e[1;38;5;#{text_color}m\u276f " : ''
    message = message.rjust(message.length + 2 * @level)
    puts "#{prefix}\e[0;38;5;#{text_color}m#{message}\e[0m"

    write_log_file(message)
  end

  def self.error(message)
    prefix = @level.zero? ? "\e[1;31m\u276f " : ''
    message = message.rjust(message.length + 2 * @level)
    puts "#{prefix}\e[0;31m#{message}\e[0m"
    write_log_file("Error: #{message}")
  end

  def self.init
    `mkdir -p #{ENV['HOME']}/.dotfiles-local/stacked-log`

    current_dir = Dir.pwd.split('/').last
    @log_path = "#{ENV['HOME']}/.dotfiles-local/stacked-log/#{current_dir}.log"
  end

  def self.write_log_file(message)
    current_datetime = DateTime.now.iso8601
    File.open(@log_path, 'a') { |f| f.puts "#{current_datetime} #{message.gsub(/\e\[.*?m/, '')}" }
  end
end

module OS
  def self.mac?
    (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def self.linux?
    (/linux/ =~ RUBY_PLATFORM) != nil
  end
end

class RebaseError < StandardError
  def initialize(branch)
    super("Rebase failed for #{branch}")
  end
end

class FastForwardError < StandardError
  def initialize(branch)
    super("Fast-forward merge failed for #{branch}")
  end
end

class CheckoutError < StandardError
  def initialize(branch)
    super("Checkout failed for #{branch}")
  end
end

CONFIG_PATH = File.join(Dir.pwd, 'stacked.yaml')

def config
  unless File.exist?(CONFIG_PATH)
    Logger.error 'Config not found, run "stacked init" first'
    exit 1
  end

  YAML.load_file(CONFIG_PATH)
end

def update_config(config)
  current = File.exist?(CONFIG_PATH) ? YAML.load_file(CONFIG_PATH) : {}
  File.write(CONFIG_PATH, current.merge(config).to_yaml)
end

def stack
  config['stack']
end

def stack_base_ref
  config['baseRef']
end

def parent_branch(branch_name)
  branch_index = stack.index(branch_name)
  raise 'Branch not found' unless branch_index

  return stack.at(branch_index - 1) if branch_index.positive?

  'main'
end

def check_pending_operation
  # see also https://stackoverflow.com/questions/3921409/how-to-know-if-there-is-a-git-rebase-in-progress
  git_dir = `git rev-parse --git-dir`.strip
  raise 'Rebase in progress' if Dir.exist?("#{git_dir}/rebase-merge") || Dir.exist?("#{git_dir}/rebase-apply")

  # `git rev-parse --verify CHERRY_PICK_HEAD &>/dev/null`
  # raise 'Cherry-Pick in progress' if $CHILD_STATUS.success?

  # `git rev-parse --verify MERGE_HEAD &>/dev/null`
  # raise 'Merge in progress' if $CHILD_STATUS.success?

  # `git rev-parse --verify REVERT_HEAD &>/dev/null`
  # raise 'Revert in progress' if $CHILD_STATUS.success?

  # `git rev-parse --verify REBASE_HEAD &>/dev/null`
  # raise 'Rebase in progress' if $CHILD_STATUS.success?
end

def keep_current_branch
  current_branch = `git branch --show-current`.strip
  yield
  `git checkout #{current_branch}`
end

def stack_refs(start_index)
  stack.drop(start_index).map { |branch| [branch, `git rev-parse --short #{branch}`.strip] }
end

# Why "(Make sure running this cmd on the branch which got an update)":
# git rebase --update-refs is only possible when updating always the base branch of the stack, not for anyone in the middle, see below
# Scenario: 4 branches, A, B, C, D
# If C has been updated and the following is run:
# git checkout D
# git rebase A --update-refs
# --> nothing happens, because D is already on top of A, any updated branch in-between is ignored
def sync
  check_pending_operation

  Logger.log 'Syncing stack (Make sure running this cmd on the branch which got an update)' do
    keep_current_branch do
      current_branch = `git branch --show-current`.strip
      stack_start = stack.index(current_branch)

      `git checkout #{stack.last}`
      raise CheckoutError, stack.last unless $CHILD_STATUS.success?

      Logger.log 'Old refs' do
        stack_refs(stack_start + 1).each do |(branch, ref)|
          Logger.log "#{branch}: #{ref.accent}"
        end
      end

      `git rebase #{current_branch} --update-refs --autostash`
      raise RebaseError, current_branch unless $CHILD_STATUS.success?

      Logger.log 'New refs' do
        stack_refs(stack_start + 1).each do |(branch, ref)|
          Logger.log "#{branch}: #{ref.accent}"
        end
      end

      Logger.log `git push --force-with-lease origin #{stack.drop(1).join(' ')} 2>&1`

      Logger.success 'Done.'
    end
  end
rescue StandardError => e
  Logger.error "#{e.message}, aborting"
end

def update
  check_pending_operation

  keep_current_branch do
    Logger.log 'Rebasing stack to updated base branch' do
      base = stack.at(0)
      first_branch = stack.at(1)

      Logger.log 'Fetching repository'
      `git fetch origin #{base}`

      Logger.log 'Updating base branch'
      `git checkout #{base}`
      raise CheckoutError, base unless $CHILD_STATUS.success?

      `git merge --ff-only`
      unless $CHILD_STATUS.success?
        Logger.log "Fast-Forward of #{base} not possible, falling back to rebase..."
        `git rebase`
        raise RebaseError, base unless $CHILD_STATUS.success?
      end

      # Use rebase --onto
      `git checkout #{first_branch}`
      raise CheckoutError, first_branch unless $CHILD_STATUS.success?

      Logger.log "Old ref of #{first_branch}: #{`git rev-parse --short #{first_branch}`.accent}"

      `git rebase #{stack_base_ref} --onto #{base} --autostash`
      raise RebaseError, first_branch unless $CHILD_STATUS.success?

      Logger.log "New ref of #{first_branch}: #{`git rev-parse --short #{first_branch}`.strip.accent}"
      # --

      base_ref = `git rev-parse --short #{base}`.strip
      Logger.log "Update base ref from #{stack_base_ref} to #{base_ref}"
      update_config('baseRef' => base_ref)

      `git checkout #{first_branch}`
      raise CheckoutError, first_branch unless $CHILD_STATUS.success?

      sync

      Logger.success 'Done.'
    end
  end
rescue StandardError => e
  Logger.error "#{e.message}, aborting"
end

def init
  return if File.exist?(CONFIG_PATH)

  current_branch = `git branch --show-current`.strip
  stack = ['main']
  stack.push(current_branch) if current_branch != 'main'
  base_ref = `git rev-parse --short #{stack.at(0)}`.strip
  update_config('stack' => stack, 'baseRef' => base_ref)
end

def branch(name)
  `git checkout -b #{name}`
  update_config('stack' => [*stack, name])
end

def pr
  current_branch = `git branch --show-current`.strip
  `git push --set-upstream origin #{current_branch}`
  `gh pr create --web --base #{parent_branch(current_branch)}`
end

# index: absolute number (1, 2) or relative number (-1, +2) or the word 'last'
# if ommitted, a fuzzy search via fzf is started
def checkout(index = nil)
  queue_without_base = stack.drop(1)

  if index.nil?
    branches_list = queue_without_base.map { |x| "\"#{x}\"" }.join(' ')
    branch = `items=(#{branches_list}); printf "%s\n" "${items[@]}" | fzf`
    `git checkout #{branch}`
    return
  end

  if index == 'last'
    `git checkout #{queue_without_base.last}`
    return
  end

  if !index.start_with?(/\+|-/) && !index.integer?
    Logger.error 'Invalid index'
    exit 1
  end

  if index.start_with?(/\+|-/)
    current_branch = `git branch --show-current`.strip
    current_branch_index = queue_without_base.find_index(current_branch)
    `git checkout #{queue_without_base.at(current_branch_index + index.to_i)}`
  else
    `git checkout #{queue_without_base.at(index.to_i)}`
  end
end

def parent
  current_branch = `git branch --show-current`.strip
  puts parent_branch(current_branch)
end

def open
  cmd = OS.linux? ? 'xdg-open' : 'open'
  remote = `git remote get-url origin`.strip
  org_and_repo = remote[/:(.*)\.git/, 1]

  stack.drop(1).each do |branch|
    `#{cmd} https://github.com/#{org_and_repo}/pull/#{branch}`
  end
end

def edit
  system(ENV['EDITOR'], CONFIG_PATH)
end

def help
  puts 'init - Initialize stacked in this directory'
  puts 'branch - Create a new branch at the top of this stack'
  puts 'pr - Create a GitHub PR for the stack'
  puts 'parent - Print the parent of the current branch in this stack'
  puts '[-, +, -<number>, +<number>] - Checkout a branch relative to the current one in the stack'
  puts '[last, <number>] - Checkout a branch in the stack'
  puts 'open - Open the GitHub PR for the current branch in your browser'
  puts 'edit - Edit the stacked.yaml file in your system editor'
  puts 'update - Update local stack if remote has changed'
  puts 'sync - Sync local stack changes to remote'
  puts 'help - Print this help information'
end

def run
  `command -v gh &>/dev/null`
  unless $CHILD_STATUS.success?
    Logger.error 'GitHub CLI (gh) not found in PATH, please install it first'
    exit 1
  end

  `gh auth status &>/dev/null`
  unless $CHILD_STATUS.success?
    Logger.error 'GitHub CLI (gh) not authenticated, please run "gh auth login" first'
    exit 1
  end

  command = ARGV[0]

  if %w[init branch pr parent open edit update sync help].include?(command)
    send(command, *ARGV[1..])
  elsif command == '-'
    checkout('-1')
  elsif command == '+'
    checkout('+1')
  else
    checkout(ARGV[0])
  end
end

Logger.init
run
